# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      detail:
        type: string
        required: false

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependency
        run: npm ci
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

  test-unit:
    name: Run unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependency
        run: npm ci
      - name: Run unit test
        run: npm run test-unit
  test-integration:
    name: Run integration test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependency
        run: npm ci
      - name: Compile
        run: npm run compile && npm run compile-tests-skip-libcheck
      - name: Run integration test (headless)
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test-integration
