name: Release New Version

on:
  push:
    tags:
      - '*'

jobs:
  call-lint-and-test:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      security-events: write
      actions: read
